### ISSUE TITLE
Normalize `assert*()` calls in tests

### ISSUE THREAD

**Issue by IonBazan** [doctrine/mongodb-odm#2441]
### Improvement

Currently `assert*()` calls are inconsistent between tests:
- `self::assert*()` (preferred)
- `static::assert*()` - good alternative for above, but tests should usually be `final` and overriding core methods is not expected
- `$this->assert*()` - this one is invalid as assertion methods are usually static

This should be enforced by static analysis/code style.

**Comment by hunomina** [comment]
I'll have a look at this 😉

**Comment by malarzm** [comment]
@hunomina I've merged your PR up to `2.5.x` branch - would you like to change all remaining calls there? We had few features added to 2.5.x that were not present on 2.4.x.

**Comment by hunomina** [comment]
Oh! Sure, I can have a look 😉

**Comment by IonBazan** [comment]
@hunomina I think you missed a few hidden spots where we still call them non-statically:
https://github.com/doctrine/mongodb-odm/blob/5fcca6cc7e5e93bd6d2f3ee4a2f08ca9e1689939/tests/Doctrine/ODM/MongoDB/Tests/Events/PreUpdateEventArgsTest.php#L74-L110

and

https://github.com/doctrine/mongodb-odm/blob/5fcca6cc7e5e93bd6d2f3ee4a2f08ca9e1689939/tests/Doctrine/ODM/MongoDB/Tests/Events/LifecycleListenersTest.php#L240-L270

There are quite camouflaged so it's really hard to spot them but we will be able to remove the `$phpunit` property completely there.

Can you submit a PR fixing those for `2.4.x`?

BTW these listeners could perhaps be potentially replaced by anonymous classes.

**Comment by hunomina** [comment]
I searched for occurrences using `\$this->.*assert` this time.

I could only find two of them. PR coming right up 😄

**Comment by hunomina** [comment]
There you go.
I'll create another PR to fix 2.5.x 😉

**Comment by IonBazan** [comment]
I think we can close it here
